# site properties and page defaults
title: Heidar-Zadeh Group
subtitle: Queen's University
description: Our research focuses on developing new mathematical tools, numerical algorithms, and computer software to qualitatively and quantitatively predict the outcome of chemical phenomena using strategies from quantum chemistry and machine learning.
header: images/background.jpg
footer: images/background.jpg

# site social media and other links
links:
  email: farnaz.heidarzadeh@queensu.ca
  orcid: 0000-0002-2069-050X
  google-scholar: JlIWcccAAAAJ&hl
  github: qtchem
  twitter: qtchem
  youtube: qtchem

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: false
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
